# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy Release to PyPI

on:
  release:
    types: [published]

jobs:
  test_pypi_upload:
    uses: ./.github/workflows/PyPI_package_upload.yaml
    with:
      workflow-environment: Dev
      pypi-url: https://test.pypi.org/legacy/
    permissions:
      id-token: write

  prod_pypi_upload:
    needs: test_pypi_upload
    uses: ./.github/workflows/PyPI_package_upload.yaml
    with:
      workflow-environment: Prod
      pypi-url: https://upload.pypi.org/legacy/
    permissions:
      id-token: write
